#!/bin/bash

# Daniel Jones - 7929997 - Sandwich Ordering Service 

set -e # using the options command to abort script at first error
echo
echo "PRE-COMMIT HOOK TRIGGERED"

# Check for errors detected by the linter
if ./node_modules/.bin/eslint . | grep "a"; then
	echo "Fix linting errors before committing"
	exit 1
else
	echo "Code successfully linted"
	exit 0
fi

# Check for errors detected by unit testing
if ./node_modules/.bin/ava | grep "fail"; then
	echo "One or more tests failed - fix errors before comitting"
	exit 1
else
	echo "Tests successfully passed"
	exit 0
fi

# check for master branch merging
branch="$(git rev-parse --abbrev-ref HEAD)"
if [[ $2 == 'merge' ]]; then
	echo "merging branch"
	if [[ "$branch" == "master" ]]; then
		echo "  trying to merge into the 'master' branch"
		echo "  you should push the local branch to GitHub"
		echo "  and merge to master using a pull request"
		echo
		exit 1
	fi
fi

# check for master branch commit
if [ "$branch" = "master" ]; then
	read -p "  You are about to commit to the master branch, are you sure? [y|n] " -n 1 -r < /dev/tty
	echo
	if echo $REPLY | grep -E '^[Yy]$' > /dev/null
	then
		exit 0 # commit will execute
	fi
	exit 1 # commit will not execute
fi

echo "Commit successful :-)"
